_wandb:
    value:
        cli_version: 0.21.1
        e:
            ht822085lzadp2z1j13dv7odfpno1v1z:
                codePath: multi_kinase_optuna.py
                codePathLocal: multi_kinase_optuna.py
                cpu_count: 12
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "982820896768"
                        used: "210597744640"
                email: sebastien.sueron@orange.fr
                executable: /usr/bin/python3
                git:
                    commit: 69729ddc98744e8bb82d39e87f9f3390c364bfd1
                    remote: https://github.com/ssueron/kin_cnn.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-ff215cc7-dc1b-af08-a2a7-0971db1299ce
                host: postdoc-bluechip
                memory:
                    total: "67151904768"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/postdoc/Documents/kinase_selectivity/kin_cnn/multi_kinase_optuna.py
                python: CPython 3.10.12
                root: /home/postdoc/Documents/kinase_selectivity/kin_cnn
                startedAt: "2025-08-14T18:33:32.293513Z"
                writerId: ht822085lzadp2z1j13dv7odfpno1v1z
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 300
learning_rate:
    value: 0.0004886680520007501
n_kinases:
    value: 357
