_wandb:
    value:
        cli_version: 0.21.1
        e:
            2yumum5qhxy8xgrg8ogefgozleaittdu:
                codePath: vegfr2_optuna.py
                codePathLocal: vegfr2_optuna.py
                cpu_count: 12
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "982820896768"
                        used: "207218421760"
                email: sebastien.sueron@orange.fr
                executable: /usr/bin/python3
                git:
                    commit: 69729ddc98744e8bb82d39e87f9f3390c364bfd1
                    remote: https://github.com/ssueron/kin_cnn.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-ff215cc7-dc1b-af08-a2a7-0971db1299ce
                host: postdoc-bluechip
                memory:
                    total: "67151904768"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/postdoc/Documents/kinase_selectivity/kin_cnn/vegfr2_optuna.py
                python: CPython 3.10.12
                root: /home/postdoc/Documents/kinase_selectivity/kin_cnn
                startedAt: "2025-08-14T13:45:22.413440Z"
                writerId: 2yumum5qhxy8xgrg8ogefgozleaittdu
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 5
                - 35
                - 53
            "2":
                - 1
                - 2
                - 5
                - 35
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 16
dense_layer_size:
    value: 1024
dropout:
    value: 0.30632339742346976
embedding_dim:
    value: 128
epochs:
    value: 150
kernel_size:
    value: 6
learning_rate:
    value: 0.008527090566733082
n_filters:
    value: 32
n_layers:
    value: 4
